

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    expected-client-renewal-interval-seconds: 30   # expected heartbeats frequency
    renewal-threshold-update-interval-ms: 1000  # job to calculate renewal-percent-threshold
    renewal-percent-threshold: 0.85            # rate of heartbeats from all clients in a minute
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 1000        # job to evict expired instances with no heartbeats
#    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: localhost
    appname: eureka-server
    prefer-ip-address: true

logging:
  level:
    com.netflix.eureka.registry: OFF

spring:
  application:
    name: eureka-server

dekorate:
  kubernetes:
    name: eureka-server
    server-type: LoadBalancer
    liveness-probe:
      http-action-path: /actuator/health
    readiness-probe:
      http-action-path: /actuator/health
      period-seconds: 4
    expose: false
    image-pull-policy: IfNotPresent

management:
  endpoints:
    web:
      exposure:
        include: '*'
